package com.amf.pocsecured.di.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import androidx.lifecycle.ViewModel;
import dagger.MapKey;

/**
 * Annotation to be applied to a getter or setter function, that is stored in the binary output.
 * A {@link ViewModelKey} object will be the key in a Map generated by Dagger. The value will be the
 * ViewModel to be retrieved based on the key.
 */
@MapKey
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD})
public @interface ViewModelKey
{
	Class<? extends ViewModel> value();
}
